import footerImg from '../../fonts/logo/Banner para LinkedIn marca personal rosa, lila, blanco.png';
import logo from '../../fonts/logo/nextlogo.png';
import useMediaQuery from '../../hooks/useMediaQuery';
import logInGirlImage from '/public/login-girl.png';
import { LogosGoogleIcon, LogosLinkedinIcon } from '@/components/Icons';
import Navbar from '@/components/Navbar';
import styles from '@/styles/Login.module.css';
import { motion } from 'framer-motion';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';

export default function LogIn() {
  const isDesktop = useMediaQuery('(min-width: 768px)');

  return (
    <>
      <Head>
        <title>NextStep</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <motion.div
          className={styles.container}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1 }}
        >
          <div className={styles.rectangle}>
            <Image
              src={logInGirlImage}
              alt="girl standing with a phone in her hand"
            />
          </div>
        </motion.div>
        <div className={styles.button__container}>
          <motion.button
            className={styles.button}
            initial={{ opacity: 0, x: 100 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
          >
            <LogosGoogleIcon />
            Log in with Google
          </motion.button>
          <motion.button
            className={styles.button}
            initial={{ opacity: 0, x: -100 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
          >
            <LogosLinkedinIcon />
            Log in with LinkedIn
          </motion.button>
        </div>
        <footer>
          {isDesktop ? (
            <Image
              src={footerImg}
              alt="NextStep logo"
              style={{ objectFit: 'cover' }}
            />
          ) : (
            <Image
              src={logo}
              alt="NextStep logo"
              height={100}
              width={100}
              style={{ objectFit: 'cover' }}
            />
          )}
        </footer>
      </main>
    </>
  );
}
